name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: clone repo into ec2 server
      run: git clone https://github.com/TirthMesariya/Face_recognization.git
    - name: install docker on server ec2
      run: |
               sudo apt-get update
                 sudo apt-get install -y \
                    ca-certificates \
                     curl \
                      gnupg \
                       lsb-release
                                sudo apt-get update
                          curl -fsSL https://get.docker.com | sudo sh

                          sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

                               sudo usermod -aG docker $USER
                                 newgrp docker
    - name: docker run 
      run: docker build -t demo .

    - name: docker container
      run: docker run --name admin -p 80:80 demo 
                                
            
